// Code generated by "stringer -output stringers.go -type Event"; DO NOT EDIT.

package authboss

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EventRegister-0]
	_ = x[EventAuth-1]
	_ = x[EventAuthHijack-2]
	_ = x[EventOAuth2-3]
	_ = x[EventAuthFail-4]
	_ = x[EventOAuth2Fail-5]
	_ = x[EventRecoverStart-6]
	_ = x[EventRecoverEnd-7]
	_ = x[EventGetUser-8]
	_ = x[EventGetUserSession-9]
	_ = x[EventPasswordReset-10]
	_ = x[EventLogout-11]
	_ = x[EventTwoFactorAdded-12]
	_ = x[EventTwoFactorRemoved-13]
}

const _Event_name = "EventRegisterEventAuthEventAuthHijackEventOAuth2EventAuthFailEventOAuth2FailEventRecoverStartEventRecoverEndEventGetUserEventGetUserSessionEventPasswordResetEventLogoutEventTwoFactorAddedEventTwoFactorRemoved"

var _Event_index = [...]uint8{0, 13, 22, 37, 48, 61, 76, 93, 108, 120, 139, 157, 168, 187, 208}

func (i Event) String() string {
	if i < 0 || i >= Event(len(_Event_index)-1) {
		return "Event(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Event_name[_Event_index[i]:_Event_index[i+1]]
}
