// Code generated by "stringer -output stringers.go -type Event,Interrupt"; DO NOT EDIT.

package authboss

import "strconv"

const _Event_name = "EventRegisterEventAuthEventOAuthEventAuthFailEventOAuthFailEventRecoverStartEventRecoverEndEventGetUserEventGetUserSessionEventPasswordReset"

var _Event_index = [...]uint8{0, 13, 22, 32, 45, 59, 76, 91, 103, 122, 140}

func (i Event) String() string {
	if i < 0 || i >= Event(len(_Event_index)-1) {
		return "Event(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Event_name[_Event_index[i]:_Event_index[i+1]]
}

const _Interrupt_name = "InterruptNoneInterruptAccountLockedInterruptAccountNotConfirmedInterruptSessionExpired"

var _Interrupt_index = [...]uint8{0, 13, 35, 63, 86}

func (i Interrupt) String() string {
	if i < 0 || i >= Interrupt(len(_Interrupt_index)-1) {
		return "Interrupt(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Interrupt_name[_Interrupt_index[i]:_Interrupt_index[i+1]]
}
